name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Espressif IoT Development Framework (ESP-IDF)
        uses: espressif/esp-idf-ci-action@rust-latest
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Binaries and flash info
          path: |
            build/*.bin
            build/*.elf
            build/*.map
            build/flash_*args
            build/flasher_args.json
            build/bootloader/*.bin
            build/bootloader/*.elf
            build/bootloader/*.map
            build/partition_table/*.bin
